import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import Layout from "@/components/Layout";
import AnimatedText from "@/components/AnimatedText";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";

import profilePic from "../../public/images/profile/developer-pic-1.png";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark dark:text-light w-full min-h-screen">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image
                src={profilePic}
                alt="Dizitalize"
                className="w-full h-auto"
                priority
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center ">
              <AnimatedText
                text="Transformando a sua visão em realidade com código e design."
                className="!text-6xl text-left"
              />
              <p className="my-4 text-base font-medium">
                Como um habilidoso desenvolvedor full-stack, estou dedicado a
                transformar ideias em aplicações web inovadoras. Expor meus mais
                recente projetos e artigos, mostrando minha experiência em
                React.js e desenvolvimento web.
              </p>
              <div className="flex items-center self-start mt-2">
                <Link
                  href="/dummy.pdf"
                  target="_blank"
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light"
                  download={true}
                >
                  Currículo <LinkArrow className="w-6 ml-1" />
                </Link>
                <Link
                  href="mailto:efraimfonseca@gmail.com"
                  target="_blank"
                  className="text-lg ml-4 font-medium text-dark dark:text-light underline"
                >
                  Contato
                </Link>
              </div>
            </div>
          </div>
        </Layout>

        <HireMe />

        <div className="absolute right-8 bottom-8 inline-block w-24">
          <Image
            src={lightBulb}
            alt="Digitalize"
            className=" w-full h-auto"
          ></Image>
        </div>
      </main>
    </>
  );
}
